spring.application.name=notification-service
server.port=8086

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Config Server
spring.cloud.config.uri=http://localhost:8888

# RabbitMQ - will be overridden by config-server in production
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Logging
logging.level.com.notificationservice=INFO