spring.application.name=eureka-server
server.port=8761
# Eureka server should NOT register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost
eureka.server.wait-time-in-ms-when-sync-empty=0