spring.application.name=config-server
server.port=8888
# Native mode: read config files from local filesystem
spring.profiles.active=native
spring.cloud.config.server.nwative.search-locations=classpath:/configs/